### ISSUE TITLE
Index errors

### ISSUE THREAD

**Issue by ernie7334066** [gges5110/LoveLetter#9]
IndexError {index: 8, min: 0, max: 8, message: "Index out of range (8 > 7)", stack: "Error↵    at new 

**IndexError (file:///C:/Users/Ambe…earning/LoveLetter/build/main.bundle.js:63927:25)"}index: 8 max: 8 message: "Index out of range (8 > 7)"min: 0stack: "Error↵    at new IndexError** 

(file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:8395:16)↵    at ./node_modules/mathjs/lib/utils/array.js.exports.validateIndex (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:58182:11)↵    at DenseMatrix.get (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:47904:7)↵    at _get (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:47976:21)↵    at DenseMatrix.subset (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:47876:16)↵    at ArrayIndex (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:37657:22)↵    at Object.subset (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:62647:22)↵    at ReinforcementAI.getQValue (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:63905:31)↵    at ReinforcementAI.getMaxQValueSAVectorGivenSAVectors (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:63913:24)↵    at ReinforcementAI.getMaxQValueGivenSAVectors (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:63927:25)"__proto__: RangeError
    at Object../node_modules/mathjs/lib/error/IndexError.js (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:8398:24)
    at __webpack_require__ (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:20:30)
    at Object../node_modules/mathjs/lib/utils/array.js (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:58088:19)
    at __webpack_require__ (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:20:30)
    at Object../node_modules/mathjs/lib/utils/index.js (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:60099:17)
    at __webpack_require__ (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:20:30)
    at Object../node_modules/mathjs/lib/type/matrix/Matrix.js (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:49246:12)
    at __webpack_require__ (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:20:30)
    at Object../node_modules/mathjs/lib/type/matrix/index.js (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:52006:1)
    at __webpack_require__ (file:///C:/Users/Amber/Desktop/MachineLearning/LoveLetter/build/main.bundle.js:20:30)
./node_modules/mathjs/lib/utils/array.js.exports.validateIndex @ array.js:123
DenseMatrix.get @ DenseMatrix.js:160
_get @ DenseMatrix.js:232
DenseMatrix.subset @ DenseMatrix.js:132
ArrayIndex @ subset.js:50
subset @ typed-function.js:1088
getQValue @ reinforcementAI.js:176
getMaxQValueSAVectorGivenSAVectors @ reinforcementAI.js:183
getMaxQValueGivenSAVectors @ reinforcementAI.js:195
learn @ reinforcementAI.js:73
(anonymous) @ index.js:231
setTimeout (async)
nextTurn @ index.js:228
(anonymous) @ index.js:218
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

**Comment by ernie7334066** [comment]
Play History
--------------------------------------------------------------------------
Player 1

Handmaid
Guard play against 4, guessing Countess
Guard play against 2, guessing Princess

Player 2

Handmaid
Prince play against 2
Prince

Player 3 - King

Baron play against 4

Player 4 - Countess

Guard play against 1, guessing Princess
